# =============================================================================
# Neutron Bootloader - Project Atom
# build.mk  —  kernel embedder inside bootloader
#
# Organization : serene brew
# Author       : mintRaven-05
# License      : BSD-3-Clause
#
# Generated by gen_config.py from build.cfg - do not edit by hand
# =============================================================================
KERNEL_FILENAME := CUSTOM.BIN
KERNEL_VERSION_MAJOR := 1
KERNEL_VERSION_MINOR := 0
EMBED_KERNEL := 0
