# =============================================================================
# Neutron Bootloader - Project Atom
# build.mk - kernel embedder inside bootloader
#
# Organization : serene brew
# Author       : mintRaven-05
# License      : BSD-3-Clause
#
# Generated by gen_config.py from build.cfg - do not edit by hand
# =============================================================================
KERNEL_FILENAME := CUSTOM.BIN
EMBED_KERNEL := 0
