#!/usr/bin/env python3
"""
gen_config.py - Generate include/config.h from build.cfg
Reads key = value pairs from build.cfg and emits C macros for the bootloader.
Missing or invalid keys use built-in defaults.
"""

import re
import sys
from pathlib import Path

# Defaults (must match build.cfg comments / docs)
DEFAULTS = {
    "kernel_filename": '"ATOM.BIN"',
    "kernel_staging_addr": "0x100000UL",
    "kernel_load_addr": "0x200000UL",
    "kernel_max_size": "(4 * 1024 * 1024)",
    "log_level": "info",
    "ansi_colors": "true",
    "banner_text": '"Neutron Bootloader  v1.0.0"',
    "bootloader_version": '"Neutron-1.0"',
    # Whether to embed the packed kernel into the bootloader image
    # (1 = embed, 0 = load from SD / FAT32)
    "embed_kernel": "false",
}

# Log level numeric values for C
LOG_QUIET = 0
LOG_INFO = 1
LOG_DEBUG = 2


def parse_cfg(path: Path) -> dict:
    out = {}
    if not path.exists():
        return out
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            m = re.match(r"([\w\-]+)\s*=\s*(.+)", line)
            if not m:
                continue
            key, raw = m.group(1), m.group(2).strip()
            # Normalise key names: allow dashes in the file but use
            # underscores internally (e.g. "embed-kernel" -> "embed_kernel")
            key = key.replace("-", "_")
            # Strip optional quotes for string values; keep hex/numbers as-is
            if raw.startswith('"') and raw.endswith('"'):
                out[key] = raw
            elif raw in ("true", "false"):
                out[key] = "1" if raw == "true" else "0"
            elif raw in ("quiet", "info", "debug"):
                out[key] = raw
            elif re.match(r"0x[0-9A-Fa-f]+", raw):
                out[key] = raw.rstrip("UL") + "UL"
            elif raw.isdigit():
                out[key] = raw
            else:
                out[key] = raw
    return out


def main():
    root = Path(__file__).resolve().parent
    cfg_path = root / "build.cfg"
    out_path = root / "include" / "config.h"

    cfg = parse_cfg(cfg_path)
    kernel_filename_raw = cfg.get("kernel_filename", DEFAULTS["kernel_filename"])
    kernel_staging_addr = cfg.get("kernel_staging_addr", DEFAULTS["kernel_staging_addr"])
    kernel_load_addr = cfg.get("kernel_load_addr", DEFAULTS["kernel_load_addr"])
    kernel_max_size = cfg.get("kernel_max_size", DEFAULTS["kernel_max_size"])
    log_level = cfg.get("log_level", DEFAULTS["log_level"])
    ansi_colors = cfg.get("ansi_colors", DEFAULTS["ansi_colors"])
    if ansi_colors in ("1", "0"):
        ansi_colors_val = int(ansi_colors)
    else:
        ansi_colors_val = 1 if ansi_colors.lower() == "true" else 0
    banner_text = cfg.get("banner_text", DEFAULTS["banner_text"])
    raw_bootloader_version = cfg.get("bootloader_version", DEFAULTS["bootloader_version"])
    # Strip surrounding quotes if present; boot_info_t.bootloader_version has 16 bytes (15 chars + NUL)
    if raw_bootloader_version.startswith('"') and raw_bootloader_version.endswith('"'):
        raw_bootloader_version = raw_bootloader_version[1:-1]
    if len(raw_bootloader_version) > 15:
        sys.stderr.write("Warning: bootloader_version truncated to 15 characters\n")
        raw_bootloader_version = raw_bootloader_version[:15]
    bootloader_version = '"' + raw_bootloader_version + '"'

    # Embed-kernel flag: 0/1 for C and Makefile
    embed_kernel = cfg.get("embed_kernel", DEFAULTS.get("embed_kernel", "false"))
    if embed_kernel in ("1", "0"):
        embed_kernel_val = int(embed_kernel)
    else:
        embed_kernel_val = 1 if str(embed_kernel).lower() == "true" else 0

    # Kernel filename for C (as a C string literal) vs for Makefile (bare name)
    kernel_filename_c = kernel_filename_raw
    kernel_filename_mk = kernel_filename_raw
    if kernel_filename_mk.startswith('"') and kernel_filename_mk.endswith('"'):
        kernel_filename_mk = kernel_filename_mk[1:-1]

    if log_level == "quiet":
        log_level_val = LOG_QUIET
    elif log_level == "debug":
        log_level_val = LOG_DEBUG
    else:
        log_level_val = LOG_INFO

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write("""/* Generated by gen_config.py from build.cfg - do not edit by hand */
#ifndef CONFIG_H
#define CONFIG_H

#define CFG_KERNEL_FILENAME       {}
#define CFG_KERNEL_STAGING_ADDR  {}
#define CFG_KERNEL_LOAD_ADDR     {}
#define CFG_KERNEL_MAX_SIZE      {}
#define CFG_LOG_LEVEL            {}
#define CFG_ANSI_COLORS         {}
#define CFG_BANNER_TEXT         {}
#define CFG_BOOTLOADER_VERSION  {}
#define CFG_EMBED_KERNEL        {}

/* Log level constants */
#define CFG_LOG_QUIET  0
#define CFG_LOG_INFO   1
#define CFG_LOG_DEBUG  2

#if CFG_ANSI_COLORS
#define CFG_ANSI_RESET "\\x1b[0m"
#define CFG_ANSI_BOLD  "\\x1b[1m"
#define CFG_ANSI_GREEN "\\x1b[32m"
#define CFG_ANSI_CYAN  "\\x1b[36m"
#define CFG_ANSI_YELLOW "\\x1b[33m"
#define CFG_ANSI_RED   "\\x1b[31m"
#else
#define CFG_ANSI_RESET ""
#define CFG_ANSI_BOLD  ""
#define CFG_ANSI_GREEN ""
#define CFG_ANSI_CYAN  ""
#define CFG_ANSI_YELLOW ""
#define CFG_ANSI_RED   ""
#endif

#endif /* CONFIG_H */
""".format(
            kernel_filename_c,
            kernel_staging_addr,
            kernel_load_addr,
            kernel_max_size,
            log_level_val,
            ansi_colors_val,
            banner_text,
            bootloader_version,
            embed_kernel_val,
        ))

    # Also emit a small Makefile fragment so the top-level Makefile can
    # pick up the configured kernel filename and embed flag.
    build_mk_path = root / "build.mk"
    with open(build_mk_path, "w") as mk:
        mk.write("# =============================================================================\n")
        mk.write("# Neutron Bootloader - Project Atom\n")
        mk.write("# build.mk  —  kernel embedder inside bootloader\n")
        mk.write("#\n")
        mk.write("# Organization : serene brew\n")
        mk.write("# Author       : mintRaven-05\n")
        mk.write("# License      : BSD-3-Clause\n")
        mk.write("#\n")
        mk.write("# Generated by gen_config.py from build.cfg - do not edit by hand\n")
        mk.write("# =============================================================================\n")
        mk.write(f"KERNEL_FILENAME := {kernel_filename_mk}\n")
        mk.write(f"EMBED_KERNEL := {embed_kernel_val}\n")

    if len(sys.argv) > 1 and sys.argv[1] == "--verbose":
        print("Generated", out_path)


if __name__ == "__main__":
    main()
