/* Generated by gen_config.py from build.cfg - do not edit by hand */
#ifndef CONFIG_H
#define CONFIG_H

#define CFG_KERNEL_FILENAME       "CUSTOM.BIN"
#define CFG_KERNEL_STAGING_ADDR  0x100000UL
#define CFG_KERNEL_LOAD_ADDR     0x200000UL
#define CFG_KERNEL_MAX_SIZE      0x400000UL
#define CFG_LOG_LEVEL            0
#define CFG_ANSI_COLORS         1
#define CFG_BANNER_TEXT         "Neutron Bootloader  v1.1.0"
#define CFG_BOOTLOADER_VERSION  "Neutron-1.1.0"
#define CFG_EMBED_KERNEL        0

/* Log level constants */
#define CFG_LOG_QUIET  0
#define CFG_LOG_INFO   1
#define CFG_LOG_DEBUG  2

#if CFG_ANSI_COLORS
#define CFG_ANSI_RESET "\x1b[0m"
#define CFG_ANSI_BOLD  "\x1b[1m"
#define CFG_ANSI_GREEN "\x1b[32m"
#define CFG_ANSI_CYAN  "\x1b[36m"
#define CFG_ANSI_YELLOW "\x1b[33m"
#define CFG_ANSI_RED   "\x1b[31m"
#else
#define CFG_ANSI_RESET ""
#define CFG_ANSI_BOLD  ""
#define CFG_ANSI_GREEN ""
#define CFG_ANSI_CYAN  ""
#define CFG_ANSI_YELLOW ""
#define CFG_ANSI_RED   ""
#endif

#endif /* CONFIG_H */
